### ISSUE TITLE
Failed to fetch initial state: failed to reset counters: not enough devices

### ISSUE THREAD

**Issue by benda95280** [sywesk/ocea-exporter#2]
Dear,

Today it's no more under maintenance, but it's not working.
Find the error below :

```
<html>
<body>
<!--StartFragment-->
2024/05/02 18:52:51 | stdout | /usr/local/go/src/runtime/proc.go:250
-- | -- | --
2024/05/02 18:52:51 | stdout | runtime.main
2024/05/02 18:52:51 | stdout | /app/cmd/ocea-exporter/main.go:37
2024/05/02 18:52:51 | stdout | main.main
2024/05/02 18:52:51 | stdout | 2024-05-02T16:52:51.626Z FATAL ocea-exporter/main.go:37 failed to start counter fetcher {"error": "failed to fetch initial state: failed to reset counters: not enough devices"}
2024/05/02 18:52:50 | stdout | 2024-05-02T16:52:50.801Z INFO counterfetcher/fetcher.go:183 fetched local {"local_id": "2762991"}
2024/05/02 18:52:49 | stdout | 2024-05-02T16:52:49.878Z INFO counterfetcher/fetcher.go:172 found local {"local_id": "2762991"}
2024/05/02 18:52:49 | stdout | 2024-05-02T16:52:49.878Z INFO counterfetcher/fetcher.go:163 fetched resident {"first_name": "#MYNAME#", "id": "#ISmyIDConfidential?#"}
2024/05/02 18:52:48 | stdout | 2024-05-02T16:52:48.765Z INFO oceaauth/get_token_from_credentials.go:98 auth: got token from credentials
2024/05/02 18:52:47 | stdout | 2024-05-02T16:52:47.284Z INFO counterfetcher/state.go:65 log file not found, skipping load {"path": "/root/.config/ocea-exporter/state.json"}

<!--EndFragment-->
</body>
</html>
```

Regards

**Comment by benda95280** [comment]
Any news ?

**Comment by sywesk** [comment]
@benda95280 Ok so this error happens when the number of devices (the actual meters) is different from the number of fluids that your appartment has. 

Do you happen to have multiple "hot water", "heating", or "cold water" meters ? 

In any case, i've pushed a new version, v0.4.1, that addresses the other issue and adds some debugging code. To see the debug output, set the `debug` boolean at the root of your config file or use the `OCEA_EXPORTER_DEBUG` env var.

Can you give me your debug output ? There will be some private data in the output, so do not hesitate to clean it a bit beforehand. What i want to look at is the number of devices and their declared fluid, plus the output of the "local" call to see the number of declared fluids

**Comment by benda95280** [comment]
Hi!

We have 2 Cold Water, and 2 Hot Water (2 Kitchen / 2 Bath).
Will try new version, and if not fixed, will sent the debug.

Thanks,

**Comment by sywesk** [comment]
Sadly it currently doesn't support having multiple meters of the same type. But i'll have a look at how to support this, it shouldn't be a huge task

**Comment by benda95280** [comment]
Should be awsome.
Merci :)

**Comment by benda95280** [comment]
(Could you update your docker ?)
https://registry.hub.docker.com/r/sywesk/ocea-exporter/

**Comment by sywesk** [comment]
Pushed to wrong registry 😅

**Comment by sywesk** [comment]
@benda95280 can you try the v0.5.3 image ? i've implemented support for multiple meters, but as i'm not in this configuration i can't test it properly

**Comment by benda95280** [comment]
I've got 4 entities in energy.
Logs : 
```

2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:114 updated device {"fluid": "EauFroide", "value": "164.317"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:114 updated device {"fluid": "EauChaude", "value": "126.705"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:114 updated device {"fluid": "EauFroide", "value": "63.123"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:114 updated device {"fluid": "EauChaude", "value": "13.797"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:99 declared device {"fluid": "EauFroide"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:99 declared device {"fluid": "EauChaude"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:99 declared device {"fluid": "EauFroide"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.311Z INFO homeassistant/mqtt.go:99 declared device {"fluid": "EauChaude"}
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.310Z INFO homeassistant/mqtt.go:81 cleared old topics
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.310Z INFO counterfetcher/fetcher.go:165 fetched counters
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.310Z INFO counterfetcher/fetcher.go:162 no counters were updated, skipping state update
2024/06/01 23:00:49 | stdout | 2024-06-01T21:00:49.310Z INFO counterfetcher/fetcher.go:297 updated counters
2024/06/01 23:00:46 | stdout | 2024-06-01T21:00:46.867Z INFO oceaauth/get_token_from_credentials.go:98 auth: got token from credentials
2024/06/01 23:00:45 | stdout | 2024-06-01T21:00:45.512Z INFO counterfetcher/fetcher.go:61 fetch worker started
2024/06/01 23:00:45 | stdout | 2024-06-01T21:00:45.512Z INFO homeassistant/mqtt.go:40 mqtt worker started
2024/06/01 23:00:45 | stdout | 2024-06-01T21:00:45.512Z INFO ocea-exporter/metrics.go:11 prometheus exporter is disabled
2024/06/01 23:00:45 | stdout | 2024-06-01T21:00:45.512Z INFO counterfetcher/state.go:70 state successfully loaded {"path": "/root/.config/ocea-exporter/state.json"}
2024/06/01 22:00:05 | stdout | /app/pkg/homeassistant/mqtt.go:56
2024/06/01 22:00:05 | stdout | github.com/sywesk/ocea-exporter/pkg/homeassistant.(*MQTT).worker
2024/06/01 22:00:05 | stdout | 2024-06-01T20:00:05.661Z ERROR homeassistant/mqtt.go:56 failed to build mqtt client {"error": "failed to connect to mqtt broker: network Error : dial tcp: address 192.168.1.3: missing port in address"}
2024/06/01 21:59:14 | stdout | 2024-06-01T19:59:14.620Z INFO counterfetcher/fetcher.go:165 fetched counters
2024/06/01 21:59:14 | stdout | 2024-06-01T19:59:14.620Z INFO counterfetcher/state.go:34 state successfully written {"path": "/root/.config/ocea-exporter/state.json"}
2024/06/01 21:59:13 | stdout | 2024-06-01T19:59:13.999Z INFO counterfetcher/fetcher.go:212 fetched initial state
2024/06/01 21:59:13 | stdout | /app/pkg/counterfetcher/fetcher.go:75
2024/06/01 21:59:13 | stdout | github.com/sywesk/ocea-exporter/pkg/counterfetcher.(*CounterFetcher).worker
2024/06/01 21:59:13 | stdout | /app/pkg/counterfetcher/fetcher.go:201
2024/06/01 21:59:13 | stdout | github.com/sywesk/ocea-exporter/pkg/counterfetcher.(*CounterFetcher).fetchInitialState
2024/06/01 21:59:13 | stdout | /app/pkg/counterfetcher/fetcher.go:258
2024/06/01 21:59:13 | stdout | github.com/sywesk/ocea-exporter/pkg/counterfetcher.(*CounterFetcher).fetchDevices
2024/06/01 21:59:13 | stdout | 2024-06-01T19:59:13.999Z WARN counterfetcher/fetcher.go:258 found additional devices {"old_count": 0, "new_count": 4}
2024/06/01 21:59:12 | stdout | 2024-06-01T19:59:12.606Z INFO counterfetcher/fetcher.go:194 fetched local {"local_id": "2762991"}
2024/06/01 21:59:11 | stdout | 2024-06-01T19:59:11.457Z INFO counterfetcher/fetcher.go:183 found local {"local_id": "2762991"}
2024/06/01 21:59:11 | stdout | 2024-06-01T19:59:11.457Z INFO counterfetcher/fetcher.go:174 fetched resident {"first_name": "BobDylan", "id": "#####-#########-##########"}
```

Let's wait a little bit to have a few points, but seems fine :)

**Comment by sywesk** [comment]
@benda95280 it seems like there's an issue with your MQTT configuration. 

Can you change `192.168.1.3` into `192.168.1.3:1883` in your configuration ?

**Comment by benda95280** [comment]
Yep i've fixed it when saw it, and works well !
From data i'm reading on my side, it seems ocea is updated once per day :(

**Comment by sywesk** [comment]
Exactly, and it's not even reliable. Sometimes you get the update the next morning, sometimes the same day... I don't know how they run their data systems but there might be something to improve :) 

I'm going to close this issue as the problem is solved :smile:
